### ISSUE TITLE
Transitions

### ISSUE THREAD

**Issue by marlierecharlie** [brmuloot/Landing-page#3]

**Comment by lilifull** [comment]
transition choisie : #div2 {transition-timing-function: ease;}

animation choisie : div {
  width: 100px;
  height: 100px;
  background-color: red;
  animation-name: example;
  animation-duration: 4s;
}

@keyframes example {
  0%   {background-color: red;}
  25%  {background-color: yellow;}
  50%  {background-color: blue;}
  100% {background-color: green;}

**Comment by lilifull** [comment]
div {
  width: 100px;
  height: 100px;
  background: red;
  transition: width 2s;
}

div:hover {
  width: 300px;
}
